# Generated by Django 5.2.3 on 2025-06-18 14:34

import data.constants
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Desciption', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants/')),
                ('Quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Category', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Succulent', 'Succulent'), ('Cactus', 'Cactus'), ('Herb', 'Herb'), ('Flowering', 'Flowering'), ('Foliage', 'Foliage'), ('Tree', 'Tree'), ('Shrub', 'Shrub'), ('Vine', 'Vine')])),
            ],
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('Phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[(data.constants.PaymentStatus['PENDING'], data.constants.PaymentStatus['PENDING']), (data.constants.PaymentStatus['SUCCESS'], data.constants.PaymentStatus['SUCCESS']), (data.constants.PaymentStatus['FAILURE'], data.constants.PaymentStatus['FAILURE'])], default=data.constants.PaymentStatus['PENDING'], max_length=254)),
                ('provider_order_id', models.CharField(max_length=40, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=36, null=True)),
                ('signature_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=254)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data.order')),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.plant')),
            ],
        ),
    ]
