# Generated by Django 5.2.3 on 2025-06-14 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='custom_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
